import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private List<Book> books;

    public Library() {
        this(new ArrayList<Book>());
    }

    public Library(ArrayList<Book> listOfBooks) {
        this.books = listOfBooks;

    }

    public boolean someLibraryMethod() {
        return true;
    }

    public String open() {
        return "Welcome to the Library! Biblioteca is available!";
    }


    public String listAllBooks() {
        String output = "";
        for (Book book : books) {
            //outstream.println(book);
            output += book + "\n";
        }
        return output;
    }
}
