import java.io.PrintStream;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class Library {

    private PrintStream outstream;

    public Library(PrintStream outstream) {
        this.outstream = outstream;
    }

    public boolean someLibraryMethod() {
        return true;
    }

    public String getWelcomeMessage() {
        return "Welcome to the Library! Biblioteca is available! :D";
    }

    public void printWelcomeMessage(){
         outstream.println(getWelcomeMessage());
    }
}
