import org.junit.Before;
import org.junit.Test;

import java.io.PrintStream;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ptang' at '8/4/15 1:34 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/4/15 1:34 PM
 */
public class LibraryTest {
    private Library classUnderTest;
    private  PrintStream printStream;
    @Before
    public void setup(){
        printStream = mock(PrintStream.class);
        classUnderTest = new Library(printStream);
    }

    @Test public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testGetWelcomeMessage() {
        String welcomeMessage = classUnderTest.getWelcomeMessage();
        assertThat(welcomeMessage, is("Welcome to the Library! Biblioteca is available! :D"));
    }

    @Test
    public void testPrintWelcomeMessage(){
        classUnderTest.printWelcomeMessage();
        verify(printStream).println("Welcome to the Library! Biblioteca is available! :D");

    }
}
